version: 2
jobs:
  build:
    docker:
      - image: juristr/angular-ci-build:1.0.0
    steps:
      - checkout
      - run:
          name: Operating branch
          command: echo ${CIRCLE_BRANCH}
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install node packages
          command: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Building
          command: npm run build
      - run:
          name: Execute unit tests
          command: npm run test

workflows:
  version: 2
  # The build and deploy workflow
  build_and_test:
    jobs:
      - build
